#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rblineprof'
require 'rblineprof-report'


$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'rubocop'
require 'benchmark'

# すべてのRubyファイルを対象にする (gemなども計測される)
target = /./

# カレントディレクトリ以下のRubyファイルを対象にする
# target = /#{Dir.pwd}\/./

result = nil


cli = RuboCop::CLI.new
result = 0

profile = lineprof(target) do
###
time = Benchmark.realtime do
  result = cli.run
end

puts "Finished in #{time} seconds" if cli.options[:debug]
puts "exit #{result}"

###

end
LineProf.report(profile)

exit result
